name: Bug report
description: Create a report to help us improve
labels: [bug]
title: "[bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS and version
      placeholder: macOS 14.5 / Ubuntu 22.04 / Windows 11
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: 3.10.14
  - type: textarea
    id: logs
    attributes:
      label: Logs and errors
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched existing issues
          required: true
        - label: I am using the latest code from `main`
          required: true
